const state={view:'home',search:'',category:'Todas',level:'Todos',sort:'id',favorites:new Set(JSON.parse(localStorage.getItem('ladFavoritesV2')||'[]')),simIndex:0,simStep:0};
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const els={sidebar:$('#sidebar'),hamburger:$('#hamburger'),viewButtons:$$('[data-view]'),menuItems:$$('.menu-item'),homeView:$('#homeView'),statsView:$('#statsView'),patternsToolbar:$('#patternsToolbar'),patternsGrid:$('#patternsGrid'),detailView:$('#detailView'),detailContent:$('#detailContent'),backBtn:$('#backBtn'),searchInput:$('#searchInput'),categoryFilter:$('#categoryFilter'),levelFilter:$('#levelFilter'),sortFilter:$('#sortFilter'),simulatorView:$('#simulatorView'),simPatternSelect:$('#simPatternSelect'),simNext:$('#simNext'),simReset:$('#simReset'),simTitle:$('#simTitle'),simLadder:$('#simLadder'),simStep:$('#simStep'),tiaView:$('#tiaView'),favoritesView:$('#favoritesView'),favoritesGrid:$('#favoritesGrid'),aboutView:$('#aboutView'),randomPattern:$('#randomPattern'),countPatterns:$('#countPatterns'),toast:$('#toast')};
function init(){els.countPatterns.textContent=PATTERNS.length;loadCategories();loadSimulatorSelect();bindEvents();renderPatterns();setView('home')}
function bindEvents(){els.hamburger.addEventListener('click',()=>els.sidebar.classList.toggle('open'));els.viewButtons.forEach(btn=>btn.addEventListener('click',()=>setView(btn.dataset.view)));els.searchInput.addEventListener('input',e=>{state.search=e.target.value.toLowerCase();renderPatterns()});els.categoryFilter.addEventListener('change',e=>{state.category=e.target.value;renderPatterns()});els.levelFilter.addEventListener('change',e=>{state.level=e.target.value;renderPatterns()});els.sortFilter.addEventListener('change',e=>{state.sort=e.target.value;renderPatterns()});els.backBtn.addEventListener('click',()=>setView('patterns'));els.randomPattern.addEventListener('click',()=>openPattern(PATTERNS[Math.floor(Math.random()*PATTERNS.length)].id));els.simPatternSelect.addEventListener('change',e=>{state.simIndex=Number(e.target.value);state.simStep=0;renderSimulator()});els.simNext.addEventListener('click',()=>{const p=PATTERNS[state.simIndex];state.simStep=(state.simStep+1)%p.rungs.length;renderSimulator()});els.simReset.addEventListener('click',()=>{state.simStep=0;renderSimulator()})}
function loadCategories(){[...new Set(PATTERNS.map(p=>p.category))].forEach(cat=>{const o=document.createElement('option');o.value=cat;o.textContent=cat;els.categoryFilter.appendChild(o)})}
function loadSimulatorSelect(){PATTERNS.forEach((p,idx)=>{const o=document.createElement('option');o.value=idx;o.textContent=String(p.id).padStart(2,'0')+' - '+p.title;els.simPatternSelect.appendChild(o)});renderSimulator()}
function setView(view){state.view=view;els.menuItems.forEach(i=>i.classList.toggle('active',i.dataset.view===view));els.sidebar.classList.remove('open');$$('.view').forEach(el=>el.hidden=true);if(view==='home'){els.homeView.hidden=false;els.statsView.hidden=false;els.patternsToolbar.hidden=false;els.patternsGrid.hidden=false}if(view==='patterns'){els.patternsToolbar.hidden=false;els.patternsGrid.hidden=false;renderPatterns()}if(view==='simulator'){els.simulatorView.hidden=false;renderSimulator()}if(view==='tia')els.tiaView.hidden=false;if(view==='favorites'){els.favoritesView.hidden=false;renderFavorites()}if(view==='about')els.aboutView.hidden=false;window.scrollTo({top:0,behavior:'smooth'})}
function filteredPatterns(){let list=PATTERNS.filter(p=>{const blob=`${p.id} ${p.title} ${p.category} ${p.level} ${p.application} ${p.objective} ${p.inputs.join(' ')} ${p.outputs.join(' ')} ${p.memories.join(' ')} ${p.tags.join(' ')}`.toLowerCase();return(!state.search||blob.includes(state.search))&&(state.category==='Todas'||p.category===state.category)&&(state.level==='Todos'||p.level===state.level)});return list.sort((a,b)=>state.sort==='title'?a.title.localeCompare(b.title):state.sort==='level'?a.level.localeCompare(b.level)||a.id-b.id:a.id-b.id)}
function renderPatterns(){const list=filteredPatterns();els.patternsGrid.innerHTML=list.map(cardTemplate).join('')||emptyTemplate('Nenhum padrão encontrado.');bindCards(els.patternsGrid)}
function renderFavorites(){const list=PATTERNS.filter(p=>state.favorites.has(p.id));els.favoritesGrid.innerHTML=list.map(cardTemplate).join('')||emptyTemplate('Nenhum favorito marcado ainda.');bindCards(els.favoritesGrid)}
function bindCards(container){container.querySelectorAll('.pattern-card').forEach(card=>card.addEventListener('click',e=>{if(e.target.closest('.favorite-btn'))return;openPattern(Number(card.dataset.id))}));container.querySelectorAll('.favorite-btn').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();toggleFavorite(Number(btn.dataset.id));renderPatterns();if(state.view==='favorites')renderFavorites()}))}
function cardTemplate(p){const fav=state.favorites.has(p.id);return `<article class="pattern-card" data-id="${p.id}"><div class="card-top"><span class="badge">${String(p.id).padStart(2,'0')} • ${p.category}</span><span class="badge level">${p.level}</span></div><h3>${p.title}</h3><p>${p.application}</p><div class="card-meta"><span class="badge">${p.plc}</span><span class="badge">${p.language}</span></div><button class="favorite-btn ${fav?'active':''}" data-id="${p.id}" aria-label="Favoritar">${fav?'★':'☆'}</button></article>`}
function emptyTemplate(text){return `<div class="info-page" style="grid-column:1/-1"><h2>${text}</h2><p>Altere a busca ou o filtro para localizar outro padrão Siemens.</p></div>`}
function renderLadder(p,active=-1){return `<div class="ladder-render">${p.rungs.map((r,i)=>`<div class="lad-rung ${i===active?'active':''}"><div class="lad-label">${r.label}</div><div class="lad-left">${r.left.map(c=>`<span class="contact">[ ${c} ]</span>`).join('')}</div><span class="coil">( ${r.right} )</span></div>`).join('')}</div>`}
function openPattern(id){const p=PATTERNS.find(x=>x.id===id);if(!p)return;const fav=state.favorites.has(p.id);els.detailContent.innerHTML=`<span class="badge">Padrão ${String(p.id).padStart(2,'0')}</span><h2>${p.title}</h2><div class="detail-meta"><span class="badge">${p.category}</span><span class="badge level">${p.level}</span><span class="badge">${p.plc}</span><span class="badge">${p.software}</span><span class="badge">${p.language}</span></div><div class="detail-actions"><button class="secondary" id="detailFav">${fav?'★ Remover favorito':'☆ Adicionar favorito'}</button><button class="copy-btn" id="copyTags">Copiar tags</button><button class="copy-btn" id="copyLadder">Copiar lógica</button></div><div class="detail-grid"><section class="detail-section"><h3>Objetivo</h3><p>${p.objective}</p></section><section class="detail-section"><h3>Aplicação prática</h3><p>${p.application}</p><p>${p.practicalTest}</p></section><section class="detail-section"><h3>Explicação</h3><p>${p.explanation}</p></section><section class="detail-section"><h3>Passos no TIA Portal</h3><ol>${p.tiaSteps.map(x=>`<li>${x}</li>`).join('')}</ol></section><section class="detail-section"><h3>Entradas</h3><div class="tag-list">${p.inputs.map(x=>`<div class="tag-line">${x}</div>`).join('')}</div></section><section class="detail-section"><h3>Saídas, memórias e DBs</h3><div class="tag-list">${[...p.outputs,...p.memories].map(x=>`<div class="tag-line">${x}</div>`).join('')}</div></section><section class="detail-section"><h3>Checklist de teste</h3><ul>${p.checklist.map(x=>`<li>${x}</li>`).join('')}</ul></section><section class="detail-section"><h3>Erros comuns</h3><ul>${p.commonErrors.map(x=>`<li>${x}</li>`).join('')}</ul></section></div><h3 style="margin-top:24px">Desenho LAD conceitual</h3>${renderLadder(p)}<h3 style="margin-top:24px">Lógica conceitual para referência</h3><pre class="lad-box">${p.ladder}</pre>`;$$('.view').forEach(el=>el.hidden=true);els.detailView.hidden=false;$('#detailFav').addEventListener('click',()=>{toggleFavorite(p.id);openPattern(p.id)});$('#copyTags').addEventListener('click',()=>copyText([...p.inputs,...p.outputs,...p.memories].join('\n')));$('#copyLadder').addEventListener('click',()=>copyText(p.ladder));window.scrollTo({top:0,behavior:'smooth'})}
function toggleFavorite(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem('ladFavoritesV2',JSON.stringify([...state.favorites]));showToast(state.favorites.has(id)?'Adicionado aos favoritos':'Removido dos favoritos')}
async function copyText(text){try{await navigator.clipboard.writeText(text);showToast('Conteúdo copiado')}catch(e){showToast('Não foi possível copiar automaticamente')}}
function showToast(text){els.toast.textContent=text;els.toast.hidden=false;clearTimeout(window.__toast);window.__toast=setTimeout(()=>els.toast.hidden=true,1800)}
function renderSimulator(){const p=PATTERNS[state.simIndex]||PATTERNS[0];els.simTitle.textContent=String(p.id).padStart(2,'0')+' - '+p.title;els.simLadder.innerHTML=renderLadder(p,state.simStep);const r=p.rungs[state.simStep];els.simStep.innerHTML=`<strong>Etapa ${state.simStep+1}:</strong> ${r.label}. Verifique as condições ${r.left.join(', ')} para acionar ${r.right}.`}
init();